k

diff --git a/.github/workflows/debug_build.yml b/.github/workflows/debug_build.yml
--- a/.github/workflows/debug_build.yml
+++ b/.github/workflows/debug_build.yml
@@ -34,6 +34,10 @@ jobs:
         run: |
           exit_on_error() { echo "$1"; exit 1; }
           echo "Download BootStrap for The Code"
+          echo "First We Should Make A Directory"
+          cd app/src/main/
+          mkdir -p assets && echo "Make Successful" || echo "Make Failed"
+          cd ../../../
           wget -O app/src/main/assets/bootstrap-aarch64.zip https://github.com/termux/termux-packages/releases/download/bootstrap-2026.07.26-r1%2Bapt.android-7/bootstrap-aarch64.zip && echo "\nDownload Success" || echo "Download Failed"
           echo "Termux Team Origin Code Start Excute"
           echo "Setting vars"
